name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    name: PHP 8.5 - Laravel 13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl
          coverage: none

      - name: Create database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS laravel_mt_propietario;'
          mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS laravel_mt_tenant_1;'
          mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS laravel_mt_tenant_2;'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 7

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test
        env:
          DB_PASSWORD: root

      - name: Static analysis
        run: composer analyse

      - name: Code style
        run: composer format
